/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author arsan
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        
        namaField.putClientProperty("JTextField.placeholderText", "Nama sesuai KTP");
        nomorField.putClientProperty("JTextField.placeholderText", "Contoh: 08xxxxxxxxxx");
        getRootPane().setDefaultButton(pesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        nomorField = new javax.swing.JTextField();
        kotaCombo = new javax.swing.JComboBox<>();
        ekonomiRadio = new javax.swing.JRadioButton();
        bisnisRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanArea = new javax.swing.JTextArea();
        pesanButton = new javax.swing.JButton();
        temaToggle = new javax.swing.JToggleButton();
        bagasiCheck = new javax.swing.JCheckBox();
        makanCheck = new javax.swing.JCheckBox();
        asuransiCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Nomor HP");

        jLabel3.setText("Kota Tujuan");

        jLabel4.setText("Kelas");

        kotaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== PILIH KOTA TUJUAN ===", "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda, Balikpapan" }));

        ekonomiRadio.setSelected(true);
        ekonomiRadio.setText("Ekonomi");

        bisnisRadio.setText("Bisnis");

        eksekutifRadio.setText("Eksekutif");

        jLabel5.setText("Fasilitas Tambahan");

        jLabel6.setText("Catatan");

        catatanArea.setColumns(20);
        catatanArea.setRows(3);
        jScrollPane1.setViewportView(catatanArea);

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        bagasiCheck.setText("Bagasi");

        makanCheck.setText("Makan");

        asuransiCheck.setText("Asuransi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomorField)
                            .addComponent(kotaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bagasiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ekonomiRadio))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bisnisRadio)
                                    .addComponent(makanCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eksekutifRadio)
                                    .addComponent(asuransiCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(temaToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(namaField)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nomorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(kotaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ekonomiRadio)
                        .addComponent(bisnisRadio))
                    .addComponent(eksekutifRadio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(bagasiCheck)
                    .addComponent(makanCheck)
                    .addComponent(asuransiCheck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temaToggle)
                    .addComponent(pesanButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
        // TODO add your handling code here:
        gantiTema(temaToggle.isSelected());
    }//GEN-LAST:event_temaToggleActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        // TODO add your handling code here:
        tampilkanRingkasan();
    }//GEN-LAST:event_pesanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCheck;
    private javax.swing.JCheckBox bagasiCheck;
    private javax.swing.JRadioButton bisnisRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea catatanArea;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> kotaCombo;
    private javax.swing.JCheckBox makanCheck;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField nomorField;
    private javax.swing.JButton pesanButton;
    private javax.swing.JToggleButton temaToggle;
    // End of variables declaration//GEN-END:variables
    private void tampilkanRingkasan() {
        String kelas = ekonomiRadio.isSelected() ? "Ekonomi" : bisnisRadio.isSelected() ? "Bisnis" : "Eksekutif";
        
        List<String> fasilitas = new ArrayList<>();
        for (JCheckBox cb : List.of(bagasiCheck, makanCheck, asuransiCheck)) {
            if (cb.isSelected()) {
                fasilitas.add(cb.getText());
            }
        }
        String pesan = "Nama: " + namaField.getText()
        + "\nNomor: " + nomorField.getText()
        + "\nKota Tujuan: " + kotaCombo.getSelectedItem()
        + "\nKelas: " + kelas      
        + "\nFasilitas Tambahan: " + (fasilitas.isEmpty() ? "-" : String.join(", ", fasilitas))
        + "\nCatatan: " + catatanArea.getText();
        
        JOptionPane.showMessageDialog(this, pesan, "Data Tiket",
        JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void gantiTema(boolean gelap) {
        if (gelap) {
            FlatDarkLaf.setup();
        } else {
            FlatLightLaf.setup();
        }
        FlatLaf.updateUI(); // terapkan tema baru ke semua jendela yang terbuka
        temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
    }
    
}
